[workspace]
members = [
    "crates/metricchrono-consensus",
    "crates/metricchrono-core",
    "crates/metricchrono-ffi",
    "crates/metricchrono-log",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "Apache-2.0"
repository = "https://github.com/chrono-metrics/metricchrono"
homepage = "https://github.com/chrono-metrics/metricchrono"
authors = ["MetricChrono contributors"]
